### ISSUE TITLE
Support C++ files with cpp extension

### ISSUE THREAD

**Issue by zerodefect** [clearlinux/make-fmv-patch#2]
I believe that the pattern matching for files in the script is limited to .c files.  Could this be extended to support additional file types? Immediately, I can see inclusion of .cpp files to be of benefit.

**Comment by VictorRodriguez** [comment]
@zerodefect thanks for the request, please let me know if the proposed commit fix your needs . I also added a tests directory where you can send PR of examples you need support so we can reproduce easily. Let me know if this is ok so I can proceed with merge of commit

**Comment by zerodefect** [comment]
@VictorRodriguez , I'm noticing some problems, but I'm not convinced it's with your script.  I have a patch file for a .cpp file which looks like this:

`--- ../src/cps/av_input/decoders/abstract_decoder.cpp	2018-11-12 09:23:54.132350000 +0000
+++ ../src/cps/av_input/decoders/abstract_decoder.cpp~	2018-11-30 00:10:24.164276000 +0000
@@ -143,3 +143,7 @@
 
 // $CB_BEGIN_FOOTER$                                                    //
 // $CB_END_FOOTER$                                                      //
+__attribute__((target_clones("avx2","arch=atom","default")))
+__attribute__((target_clones("avx2","arch=atom","default")))
+__attribute__((target_clones("avx2","arch=atom","default")))
+__attribute__((target_clones("avx2","arch=atom","default")))
`
So a few FMV attributes have been added at the end of the file but they are 1 after the other and does not correlate to locations where code (functions and/or member functions) is defined.

This was generated on Ubuntu Bionic 18.04 using gcc v8.2 using `-O2` with `-ftree-vectorize`.

**Comment by VictorRodriguez** [comment]
@zerodefect what src are you using? i was looking for src/cps/av_input/decoders/abstract_decoder.cpp in google but could find , just let me know what git project it is and i can clone and test the script

**Comment by zerodefect** [comment]
I should have been cleare; I tried it on a few internal projects that I have. I'll either try recreate a code sample or I'll find a project on Github that produces similar results.

**Comment by VictorRodriguez** [comment]
ok, one question did the test that I upload in this PR works for you with C++ in your development environment?

**Comment by zerodefect** [comment]
Hi @VictorRodriguez , I've had an opportunity to give this PR the time it deserves.  

Firstly, I've tried to reproduce the problem that I noticed in the patch file at end of last week, but I've not been able to create a small enough example.  I'm beginning to think that a combination of default implementations (for constructors, destructors, etc) and inheritance causes this issue. It's certainly a gcc error. I think you should proceed regardless of what I am seeing though as the problem is upstream of yourself.

Secondly, I tried out the test cases.  They work nicely. Only comment here though is that when I build using `make`, I notice that the build finishes but the console pauses until I hit another key like `Enter`.

[Image can be sen here]https://ibb.co/7G9XLwm)

**Comment by VictorRodriguez** [comment]
@zerodefect you need to apply the patches that the tool generate , maybe with git am or git apply
