### ISSUE TITLE
Wrap attributes in platform checks to preserve portability

### ISSUE THREAD

**Issue by StefanHamminga** [clearlinux/make-fmv-patch#8]
The inserted attributes prevent compilation on, for example, arm.

Wrapping the inserted line in a check for x86 platforms will preserve portability:

```C++
    ...
#if defined(i386__) || defined(__i386__) || defined(_M_IX86) || defined(_M_IX86) || defined(__X86__) || defined(_X86_) || defined(__I86__) || defined(__INTEL__) || defined(__amd64__) || defined(__amd64) || defined(__x86_64__) || defined(__x86_64) || defined(_M_AMD64)
    __attribute__((target_clones("avx2","arch=atom","default")))
#endif
    ...
```

Defines taken from: https://sourceforge.net/p/predef/wiki/Architectures/

**Comment by VictorRodriguez** [comment]
@StefanHamminga let me know if https://github.com/clearlinux/make-fmv-patch/pull/11 is a way to address the portability

**Comment by StefanHamminga** [comment]
Excellent, works for me, thanks (both for addressing this and the work on this project)!
